---
language: python
python: 2.7

sudo: required
dist: xenial
env: OS=xenial

matrix:
  include:
    - os: linux
      dist: trusty
      env: OS=trusty
    - os: linux
      dist: centos
      env: OS=centos
    - os: linux
      dist: jessie
      env: OS=jessie

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/provision.yml -i tests/inventory --syntax-check

  # Run the install playbook
  - ansible-playbook tests/provision.yml -i tests/inventory -c local -e splunkforwarder_get_via_curl=yes

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
